GET http://localhost:8080/course/first
Content-Type: application/json

###
POST http://localhost:8080/course/sendKafka
Content-Type: application/json

###
POST http://localhost:8080/course/sendKafkaAsync
Content-Type: application/json

###
POST http://localhost:8080/course/subtractOffset
Content-Type: application/json

###
POST http://localhost:8080/course/subtractOffset2
Content-Type: application/json

###
POST http://localhost:8080/book/sendmail
